### ISSUE TITLE
gpu not found during image build

### ISSUE THREAD

**Issue by tthrift** [maleadt/julia-ngc#26]
First, thanks for all the amazing work you guys do. :)

I am setting up as a personal julia compute server at home on a ~headless desktop box   
running Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-88-generic x86_64).  
Everything is up to date.

While building a docker image of the repository "maleadt/julia-ngc" 
CUDAdrv.jl fails to initialize.

Building with JULIA_CUDA_VERBOSE=true  reports an exception =
> _│    could not load library "libcuda"_

Then it says it is building the CUDAnative run-time library for 9 devices.   

The test scripts the all pass when run in a container spun up from the built image. 
The container correctly identifies my card and builds a CUDAnative run-time library for it.  

> _[ Info: Testing using device Tesla K80 (compute capability 3.7.0, 11.052 GiB available memory) on CUDA driver 10.2.0 and toolkit 10.0.130
> [ Info: Building the CUDAnative run-time library for your sm_37 device, this might take a while..._

However, the device, sm_37, that it builds for does not seem to match any of devices 
considered during the image build process. 
To precompile an appropriate device library during build, should I add an argument to CUDAnative.load_runtime.()?

In any event is this the behavior you expect to see with this configuration?
Afaict the container runs properly. I'm just a curious noob.

**Comment by maleadt** [comment]
> While building a docker image of the repository "maleadt/julia-ngc"
> CUDAdrv.jl fails to initialize.
> 
> Building with JULIA_CUDA_VERBOSE=true reports an exception =
> 
> > _│    could not load library "libcuda"_

Yes, this is harmless. The package is loaded, and fails to initialize, but is not actually used. Future versions will hide this error message.



>  To precompile an appropriate device library during build, should I add an argument to CUDAnative.load_runtime.()?

Yes, I created a PR for that: https://github.com/maleadt/julia-ngc/pull/27

**Comment by tthrift** [comment]
Thankyou! for your help.  That works perfectly. ☺️
