### ISSUE TITLE
fftw permission issue

### ISSUE THREAD

**Issue by samcmill** [maleadt/julia-ngc#5]
The permissions on `/usr/local/share/julia/packages/FFTW/MJ7kl/deps/usr` are too restrictive for the non-root Docker and Singularity cases.

```
root@713f8c641f36:/usr/local/share/julia/packages/FFTW/MJ7kl/deps# ls -l
total 20
-r--r--r--. 5 root root 1731 Sep 27 21:06 build.jl
-rw-r--r--. 5 root root 6977 Sep 27 22:04 build.log
-r--r--r--. 5 root root 3614 Sep 27 21:06 build_fftw.jl
-rw-r--r--. 5 root root 1190 Sep 27 22:04 deps.jl
drwx------. 7 1000 1000   78 Sep 27 22:04 usr
```

(And strangely the owner / group are not root / root?)

@heindrickc

**Comment by maleadt** [comment]
Found the causes: https://github.com/JuliaPackaging/BinaryProvider.jl/issues/183 and https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/447
